version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Abc@12345
      POSTGRES_USER: postgres
      POSTGRES_DB: auction
    ports:
      - 5455:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo
    environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: Abc12345
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  auction-svc:
    image: hoangha1999/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: hoangha1999/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq

  identity-svc:
    image: hoangha1999/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    depends_on:
      - postgres

  gateway-svc:
    image: hoangha1999/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile

volumes:
  pgdata:
  mongodata:




