version: '3.4'

services:
  auctionservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7001:80"

  searchservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002:80"

